---
title: "BC Pharmacare's Response Inadequate"
author: "Stuart Hertzog"
date: "2018-08-08"
tags: ["glucose pumps"]
categories: ["Pharmacare"]
type: post
summary: There was hope that an NDP government would operate in a more open manner, bringing light to dark places in the Byzantine BC government bureaucracy Unfortunately, that doesn&rsquo;t seem to be the case. The response from BC Pharmacare to our detailed questions lacks any detail that isn&rsquo;t already available on its Web site.
---

<p class="subhead">
Nothing revealed that isn't already available on its web site
</p>

**BC Pharmacare is used to operating out of the public spotlight**. To an extent, this is understandable: it collects and must protect the sensitive personal medical information of British Columbians. 

**It's also understandable that its bureaucrats would want guard their public utterances** following decades of Liberal rule when access to medical services and information was steadily eroded.

**But there was hope that an NDP government would operate in a more open manner**, bringing light to dark places in the Byzantine BC governmental machinery.

**Unfortunately, that doesn't seem to be the case**. The response from BC Pharmacare to our [very detailed questions](/posts/questions-for-bcpharmacare-180627/) lacks any detail that isn't already available on its [web site](https://www2.gov.bc.ca/gov/content/health/health-drug-coverage/pharmacare-for-bc-residents).

**BC Pharmacare prefers to hide behind a blanket of bafflegab** rather than adopting the principles of [Open Government](https://opensource.com/resources/open-government). As its annual budget is many times more than the $15 million allocated to this project, its response, reproduced below, is totally inadequate.

**Here is the full text of BC Pharmacare's response**:

<div class="inline-aside">

Dear Mr. Hertzog:

Thank you for your message on behalf of DiabeticsBC. The Honourable Adrian Dix, Minister of Health has asked me to respond on his behalf.

PharmaCare recently expanded coverage of insulin pumps to people over the age of 25. To enable this expansion, the Province engaged in a competitive process to find the best value for insulin pumps in British Columbia. The result of this process is a tiered approach, in which anyone who qualifies for coverage will be provided the tier-one device (the Omnipod<sup>&reg;</sup> system) at no cost.

Patients with an exceptional clinical need, or for whom the tier-one device is not suitable, can ask their endocrinologist or diabetes specialist to submit a Special Authority request for exceptional coverage of the tier-two device (the MiniMed<sup>&reg;</sup> insulin pump). Coverage for a tier-two device depends on the rules of an individual or family’s PharmaCare plan, including any Fair PharmaCare deductible and family maximum requirements.

Both the tier-one and tier-two device were previously covered under the PharmaCare insulin pumps program, and have been in use for many years.

When a new insulin pump device is approved by Health Canada and becomes available on the market in BC, the manufacturer can submit their product for review, and potentially obtain PharmaCare coverage. In the case of insulin pumps, the device information submitted by the manufacturer is considered against a set of minimum criteria, as established in consultation with endocrinologists.

Both the tier-one and tier-two device met the requirements for listing. PharmaCare does not recognize any therapeutic advantage to one device over the other; both devices perform the function of continuous insulin infusion.

Prior to expanding insulin pump coverage, the Province provided both pump manufacturers the opportunity to offer better value for their product in return for tier-one listing. The resulting tiered system ensures that PharmaCare is able to provide a no-cost insulin pump option to any eligible person, thereby removing a cost barrier to access.

As per our correspondence earlier this year of February 23, 2018, other medical devices (such as continuous or flash glucose monitors) are, like insulin pumps, reviewed for coverage when the manufacturer submits their device for review.

Given the fiscal pressures affecting PharmaCare and the broader health system, the PharmaCare program has limited capacity to expand coverage for new benefits and must be very selective in that regard. Coverage decisions for additional medical devices are made using the best information available and after taking into account available funding.

I want to assure you that any additions or changes to PharmaCare coverage for drugs or devices are reviewed extensively in respect to, amongst other things, safety, clinical efficacy, cost-effectiveness and appropriateness.

We recognize that having a choice is important, and as part of any review process we work closely with physicians to ensure patients’ needs are met.

Sincerely,  
 
John Capelli, Executive Director,  
PharmaCare Information, Policy and Evaluation  
Pharmaceutical Services Division
 
pc: Honourable Adrian Dix

</div>
